# Generated by Django 3.1.1 on 2020-09-14 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gyr_x', models.DecimalField(decimal_places=8, default=0.111, max_digits=10)),
                ('gyr_y', models.DecimalField(decimal_places=8, default=0.111, max_digits=10)),
                ('gyr_z', models.DecimalField(decimal_places=8, default=0.111, max_digits=10)),
                ('acc_x', models.DecimalField(decimal_places=8, default=0.111, max_digits=10)),
                ('acc_y', models.DecimalField(decimal_places=8, default=0.111, max_digits=10)),
                ('acc_z', models.DecimalField(decimal_places=8, default=0.111, max_digits=10)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
